WEB_CACHE_DIR = 'C:\cygwin\home\Shawn\ImaginationEnvironment\webcache'
IMAGE_DIR = 'C:\cygwin\home\Shawn\ImaginationEnvironment\static\stored_images'
PATH_TO_STOP_WORDS_LIST = 'C:\cygwin\home\Shawn\ImaginationEnvironment\offline\stop_words.lst'
OFFLINE_DIR = 'C:\cygwin\home\Shawn\ImaginationEnvironment\offline\'
COUCHDB_CONNECTION_STRING = 'http://127.0.0.1:5984'
